create table "account"
(
	acc_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username text unique,
	firstname text,
	lastname text,
	password text,
	mobile_num text,
	admin_prev boolean,
	address text
);

create table "bills"
(
  bill_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  b_userID int REFERENCES account(acc_id) ON DELETE CASCADE,
  reading int,
  date_of_bill date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  amount decimal(8,2),
  cubic_meters int,
  status text
);

create table "groups"
(
  g_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  g_name text,
  g_admin int REFERENCES account(acc_id) ON DELETE CASCADE
);

create table "regcode"
(
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 g_id int REFERENCES groups(g_id) ON DELETE CASCADE,
 g_code text
 unique (g_id, g_code)
);

create or replace function user_credentials(in par_id text, out text, out text, out text, out BOOLEAN) returns setof record as
$$
   select firstname,lastname,mobile_num,admin_prev from "account" where acc_id::TE  XT = par_id;
$$
 language 'sql';

create or replace function register(in par_username text, in par_firstname text, in par_lastname text, in par_password text,
                                    in par_mobile text,in par_admin_prev boolean,in par_address text, in par_regkey text) returns text as
$$
  declare
    loc_res text;
    loc_grp text;

  begin
    select into loc_grp g_code from regcode where g_code = par_regkey;

    if loc_grp isnull then
      loc_res = 'Invalid Reg Code';
    else
    insert into account(username,firstname,lastname,password,mobile_num,admin_prev,address) values
      (par_username,par_firstname,par_lastname, par_password, par_mobile, par_admin_prev,par_address);
      delete from regcode where g_code = par_regkey;
    select into loc_res acc_id from account where username = par_username;
    end if;
      return loc_res;
  end;
$$
LANGUAGE plpgsql;

create or replace function register_admin(in par_username text, in par_firstname text, in par_lastname text, in par_password text,
                                    in par_mobile text,in par_admin_prev boolean,in par_g_name text,in par_address text) returns text as
$$
  declare
    loc_res text;
    loc_user int;

  begin
    insert into account(username,firstname,lastname,password,mobile_num,admin_prev,address) values
      (par_username,par_firstname,par_lastname, par_password, par_mobile, par_admin_prev,par_address);
    select into loc_user acc_id from account where username = par_username;
    insert into groups(g_name,g_admin) values(par_g_name,loc_user);
      loc_res = 'ok';
      return loc_res;
  end;
$$
LANGUAGE plpgsql;

create or replace function login(in par_username text, in par_password text) returns text as
$$
  declare
    loc_user text;
    loc_res text;
  begin
     select into loc_user acc_id from account
       where username = par_username and password = par_password;

     if loc_user isnull then
       loc_res = 'Error';
     else
       loc_res = loc_user;
     end if;
     return loc_res;
  end;
$$
LANGUAGE plpgsql;

create or replace function username_validator(in par_username text) returns text as
$$
  declare
    loc_user text;
    loc_res text;
  begin
     select into loc_user username from account
       where username = par_username;

     if loc_user isnull then
       loc_res = 'ok';
     else
       loc_res = 'exist';
     end if;
     return loc_res;
  end;
$$
LANGUAGE plpgsql;

create or replace function get_bills(in par_id text,out int, out text, out text, out int, out numeric , out int) returns setof record as
$$
   SELECT bill_id,TO_CHAR(date_of_bill, 'mm/dd/yyyy'),TO_CHAR(due_date, 'mm/dd/yyyy'),reading, amount, cubic_meters from bills
   where b_userID::text = par_id;;
$$
 language 'sql';

create or replace function get_onebill(in par_id text, out text, out text, out int, out int, out int) returns setof record as
$$
   SELECT TO_CHAR(date_of_bill, 'Mon dd, yyyy'),TO_CHAR(due_date, 'Mon dd, yyyy'),reading, amount, cubic_meters from bills
   where bill_id::text = par_id;
$$
language 'sql';

create or replace function get_allbill(in par_id text,out int, out text, out text) returns setof record as
$$
   SELECT bill_id,TO_CHAR(date_of_bill, 'mm/dd/yyyy'),TO_CHAR(due_date, 'mm/dd/yyyy') from bills
   where b_userID::text = par_id;
$$
language 'sql';

create or replace function add_bill(in par_username text, in par_password text) returns text as
$$
  declare
    loc_user text;
    loc_res text;
  begin
     select into loc_user acc_id from account
       where username = par_username and password = par_password;

     if loc_user isnull then
       loc_res = 'Error';
     else
       loc_res = loc_user;
     end if;
     return loc_res;
  end;
$$
LANGUAGE plpgsql;

--THIS SELECTS THE LATEST BILL INSERTED
-- select * from bills
-- where date_of_bill = (select max(date_of_bill) from bills)

-- select reading from bills
-- where b_userid = 1
-- order by date_of_bill desc
-- limit 1

